baseURL: "https://ageres7-dev.github.io/ageres7-dev/"
languageCode: ru-ru
title: ageres7-dev
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
pluralizeListTitles: false

googleAnalytics: G-MPCCPNVF2G

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10

params:
  env: production
  title: Sergey Dolgikh
  description: "iOS Developer"
  author: "Сергей Долгих"
  images: ["me.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowPostNavLinks: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true
  TocSide: left
  math: true
  ShowAllPagesInArchive: true
  mainSections: ["projects"]

  assets:
    disableHLJS: true

  label:
    text: "ageres7-dev"
    iconHeight: 35

  profileMode:
    enabled: true
    title: Сергей Долгих
    subtitle: "iOS Developer"
    imageUrl: "me.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: avatar

  homeInfoParams:
    Title: "Hi there 👋"
    Content: |
      Welcome to my blog

  socialIcons:
    - name: telegram
      url: "https://t.me/ageres7"
    - name: email
      url: "mailto:ageres7@gmail.com"
    - name: github
      url: "https://github.com/ageres7-dev"

  cover:
    linkFullImages: true
    hidden: false
    hiddenInList: false
    hiddenInSingle: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: projects
      name: Проекты
      url: /projects/
      weight: 1
    - identifier: posts
      name: Статьи
      url: /posts/
      weight: 2

pygmentsUseClasses: true

markup:
  tableOfContents:
    endLevel: 6
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    tabWidth: 4
